export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST"
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE"
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS"

export const POST_TASK_REQUEST = "POST_TASK_REQUEST"
export const POST_TASK_FAILURE = "POST_TASK_FAILURE"
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS"

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"